version: "3.8"

services:
  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8G

  app:
    build: .
    restart: always
    depends_on:
      - postgres
      - ollama
    environment:
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_db
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app_network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  ollama_data:
