version: '3.8'

services:
  web:
    build: .
    command: gunicorn mobtakir_website_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8094:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=mobtakir_website_django.settings
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    restart: always

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  static_volume:
  media_volume:
  ollama_data: